spring.application.name=LifeHub

spring.datasource.url=jdbc:postgresql://localhost:5433/LifeHub-DB
spring.datasource.username=postgres
spring.datasource.password=147852
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
